// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination ../mocks/ghapi.go -package=mocks -mock_names=Client=GHClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// GHClient is a mock of Client interface.
type GHClient struct {
	ctrl     *gomock.Controller
	recorder *GHClientMockRecorder
	isgomock struct{}
}

// GHClientMockRecorder is the mock recorder for GHClient.
type GHClientMockRecorder struct {
	mock *GHClient
}

// NewGHClient creates a new mock instance.
func NewGHClient(ctrl *gomock.Controller) *GHClient {
	mock := &GHClient{ctrl: ctrl}
	mock.recorder = &GHClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GHClient) EXPECT() *GHClientMockRecorder {
	return m.recorder
}

// GetFileContent mocks base method.
func (m *GHClient) GetFileContent(ctx context.Context, owner, repo, path, ref string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileContent", ctx, owner, repo, path, ref)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileContent indicates an expected call of GetFileContent.
func (mr *GHClientMockRecorder) GetFileContent(ctx, owner, repo, path, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileContent", reflect.TypeOf((*GHClient)(nil).GetFileContent), ctx, owner, repo, path, ref)
}

// GetLatestRelease mocks base method.
func (m *GHClient) GetLatestRelease(ctx context.Context, owner, repo string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestRelease", ctx, owner, repo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestRelease indicates an expected call of GetLatestRelease.
func (mr *GHClientMockRecorder) GetLatestRelease(ctx, owner, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestRelease", reflect.TypeOf((*GHClient)(nil).GetLatestRelease), ctx, owner, repo)
}

// GetLatestSHATag mocks base method.
func (m *GHClient) GetLatestSHATag(ctx context.Context, owner, repo, appName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestSHATag", ctx, owner, repo, appName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestSHATag indicates an expected call of GetLatestSHATag.
func (mr *GHClientMockRecorder) GetLatestSHATag(ctx, owner, repo, appName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestSHATag", reflect.TypeOf((*GHClient)(nil).GetLatestSHATag), ctx, owner, repo, appName)
}
