// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination ../mocks/ghapi.go -package=mockghapi
//

// Package mockghapi is a generated GoMock package.
package mockghapi

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetLatestSHATag mocks base method.
func (m *MockClient) GetLatestSHATag(ctx context.Context, owner, repo, appName string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestSHATag", ctx, owner, repo, appName)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLatestSHATag indicates an expected call of GetLatestSHATag.
func (mr *MockClientMockRecorder) GetLatestSHATag(ctx, owner, repo, appName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestSHATag", reflect.TypeOf((*MockClient)(nil).GetLatestSHATag), ctx, owner, repo, appName)
}
