repository:
  topics: webkit, payload, svelte-kit, golang
  private: false
  delete_branch_on_merge: true
  allow_merge_commit: false
teams:
  - name: core
    permission: admin
branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      enforce_admins: false
      allow_force_pushes: false
      restrictions:
        apps: []
        users: []
        teams:
          - core
