repository:
  topics: webkit, payload, svelte-kit, golang
  private: false
  delete_branch_on_merge: true
  allow_merge_commit: false
teams:
  - name: core
    permission: admin
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      required_status_checks: null
      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams:
          - core
