name: "CI Setup"
description: "Checkout, setup Go, Node, and dependencies"

inputs:
  integration:
    description: "Whether to run full integration setup (brew, sops, dependencies)"
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.25.3"
        cache: true

    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: "lts/*"

    - name: Install Brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      shell: bash

    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: "10.19.0"
        run_install: false

    - name: Setup Biome
      uses: biomejs/setup-biome@v2
      with:
        # This should match the schema version defined in boime.json
        version: "1.8.3"

    - name: Install dependencies
      if: ${{ inputs.integration == 'true' }}
      shell: bash
      run: |
        export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
        make setup

    - name: Install sops
      if: ${{ inputs.integration == 'true' }}
      shell: bash
      run: |
        curl -LO https://github.com/getsops/sops/releases/download/v3.11.0/sops-v3.11.0.linux.amd64
        mv sops-v3.11.0.linux.amd64 /usr/local/bin/sops
        chmod +x /usr/local/bin/sops

    - name: Install Terraform
      if: ${{ inputs.integration == 'true' }}
      uses: hashicorp/setup-terraform@v3
      with:
        # NOTE: Keep this version in sync with internal/infra/tf.go (TerraformVersion constant)
        terraform_version: "1.13.0"
