package manifest

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"time"

	"github.com/spf13/afero"

	"github.com/ainsleydev/webkit/internal/printer"
)

type (
	// Manifest tracks all files generated by WebKit, including their source
	// and content hashes for drift detection.
	Manifest struct {
		Version     string               `json:"version"` // Webkit CLI version
		GeneratedAt time.Time            `json:"generated_at"`
		Files       map[string]FileEntry `json:"files"` // Filepath to Entry
	}
	// FileEntry represents a single generated file and its metadata.
	// Used to track what generated the file, what caused it to be generated,
	// and whether its content has changed since generation.
	FileEntry struct {
		Path         string    `json:"path"`         // Relative path to the generated file
		Generator    string    `json:"generator"`    // e.g. "cicd.BackupWorkflow", "files.PackageJSON"
		Source       string    `json:"source"`       // What in app.json caused this? e.g., "resource:postgres-prod"
		Hash         string    `json:"hash"`         // SHA256 of content for drift detection
		ScaffoldMode bool      `json:"scaffolded"`   // Whether file was created in scaffold mode (won't overwrite)
		GeneratedAt  time.Time `json:"generated_at"` // When this file entry was created/updated
	}
)

// Cleanup removes files that are no longer needed by WebKit by comparing
// the old and new manifests.
func Cleanup(fs afero.Fs, old, new *Manifest, console *printer.Console) error {
	for path, entry := range old.Files {
		// Don't try and hash stuff that's managed by the
		// user and not WebKit.
		if entry.ScaffoldMode {
			continue
		}

		// File existed before but doesn't exist now = orphaned.
		_, exists := new.Files[path]
		if exists {
			continue
		}

		console.Warn(fmt.Sprintf("Removing orphaned: %s", path))

		if err := fs.Remove(path); err != nil {
			return fmt.Errorf("removing %s: %w", path, err)
		}

		console.Success(fmt.Sprintf("Removed: %s", path))
	}

	return nil
}

// HashContent generates a SHA256 hash of the provided data.
// Used to detect if file contents have changed since generation.
func HashContent(data []byte) string {
	hash := sha256.Sum256(data)
	return hex.EncodeToString(hash[:])
}
