# GoReleaser configuration for webkit CLI
# Documentation: https://goreleaser.com


version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

# Main Build
# See: https://goreleaser.com/customization/builds/
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: webkit
    ignore:
      - goos: windows
        goarch: arm64
    tags:
      - prod
    ldflags:
      - -s -w
      - -X github.com/ainsleydev/webkit/internal/version.Version={{.Version}}
      - -X github.com/ainsleydev/webkit/internal/version.Commit={{.Commit}}
      - -X github.com/ainsleydev/webkit/internal/version.Date={{.Date}}
      - -X github.com/ainsleydev/webkit/internal/version.BuiltBy=goreleaser
archives:
  - formats: [tar.gz]
    # This name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Refactors'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Others'
      order: 999

release:
  draft: false
  github:
    owner: ainsleydev
    name: webkit
  name_template: "{{.ProjectName}} v{{.Version}}"
  footer: |
    ---

    **Full Changelog**: https://github.com/ainsleydev/webkit/compare/{{.PreviousTag}}...{{.Tag}}

    ## Installation

    Download the appropriate binary for your platform from the assets below.

    ### Using Go
    ```bash
    go install github.com/ainsleydev/webkit/cmd/webkit@{{.Tag}}
    ```
