package version

import (
	"fmt"
	"time"

	"github.com/spf13/afero"

	"github.com/ainsleydev/webkit/internal/scaffold"
)

// GenerateVersionFile creates a version.gen.go file with the provided version information.
// This is used to inject version details at build time without relying on ldflags.
func GenerateVersionFile(fs afero.Fs, gen scaffold.Generator, versionInfo VersionInfo) error {
	content := fmt.Sprintf(`// Code generated by WebKit version generator. DO NOT EDIT.
package version

// generatedVersion contains the version information injected at build time.
const (
	generatedVersion = %q
	generatedCommit  = %q
	generatedDate    = %q
	generatedBuiltBy = %q
)
`, versionInfo.Version, versionInfo.Commit, versionInfo.Date, versionInfo.BuiltBy)

	return gen.Code("internal/version/version.gen.go", content)
}

// VersionInfo holds the build-time version information.
type VersionInfo struct {
	Version string
	Commit  string
	Date    string
	BuiltBy string
}

// DefaultVersionInfo returns default version information for local development.
func DefaultVersionInfo() VersionInfo {
	return VersionInfo{
		Version: "v0.0.1-dev",
		Commit:  "none",
		Date:    time.Now().Format(time.RFC3339),
		BuiltBy: "local",
	}
}
