// Code generated by WebKit version generator. DO NOT EDIT.
package version

// generatedVersion contains the version information injected at build time.
const (
	generatedVersion = "v0.0.1-dev"
	generatedCommit  = "none"
	generatedDate    = "unknown"
	generatedBuiltBy = "local"
)
