name: 'Setup WebKit Repository'
description: 'Reads webkit_version from app.json and checks out the WebKit repository at that version'

outputs:
  version:
    description: 'The WebKit version being used'
    value: ${{ steps.read-version.outputs.version }}
  webkit-path:
    description: 'Path to the checked out WebKit repository'
    value: ${{ steps.set-path.outputs.path }}

runs:
  using: 'composite'
  steps:
    - name: Read WebKit Version
      id: read-version
      shell: bash
      run: |
        WEBKIT_VERSION=$(jq -r '.webkit_version // "latest"' "app.json")
        echo "version=$WEBKIT_VERSION" >> $GITHUB_OUTPUT
        echo "Detected WebKit version: $WEBKIT_VERSION"

    - name: Checkout WebKit Repository
      id: checkout-webkit
      uses: actions/checkout@v5
      with:
        repository: 'ainsleydev/webkit'
        ref: ${{ steps.read-version.outputs.version }}
        path: '.webkit-repo'

    - name: Set WebKit Path Output
      id: set-path
      shell: bash
      run: |
        echo "path=.webkit-repo" >> $GITHUB_OUTPUT
