- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow SSH, HTTP, HTTPS
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - 22
    - 80
    - 443

- name: Enable UFW
  ufw:
    state: enabled
