// Package manifest provides file tracking and drift detection for WebKit-generated files.
//
// The manifest system tracks all files generated by WebKit, storing metadata about
// each file including its source (what in app.json caused it to be generated),
// the generator that created it, and a content hash for detecting manual modifications.
//
// # Drift Detection
//
// The package can detect several types of drift:
//   - Modified: Files that have been manually edited after generation
//   - Outdated: Files that need regeneration due to app.json changes
//   - New: Files that should exist but are missing
//   - Deleted: Files that are no longer needed and should be removed
//
// # Manifest Format
//
// The manifest is stored as JSON in .webkit/manifest.json and includes:
//   - WebKit version that generated the files
//   - Timestamp of generation
//   - Map of file paths to their metadata (generator, source, hash, scaffold mode)
//
// Scaffold mode files are tracked but never overwritten or removed automatically,
// allowing users to customize them after initial generation.
package manifest
