package manifest

import (
	"crypto/sha256"
	"encoding/hex"
	"time"
)

type (
	// Manifest tracks all files generated by WebKit, including their source
	// and content hashes for drift detection.
	Manifest struct {
		Version     string               `json:"version"` // Webkit CLI version
		GeneratedAt time.Time            `json:"generated_at"`
		Files       map[string]FileEntry `json:"files"` // Filepath to Entry
	}
	// FileEntry represents a single generated file and its metadata.
	// Used to track what generated the file, what caused it to be generated,
	// and whether its content has changed since generation.
	FileEntry struct {
		Path         string    `json:"path"`         // Relative path to the generated file
		Generator    string    `json:"generator"`    // e.g. "cicd.BackupWorkflow", "files.PackageJSON"
		Source       string    `json:"source"`       // What in app.json caused this? e.g., "resource:postgres-prod"
		Hash         string    `json:"hash"`         // SHA256 of content for drift detection
		ScaffoldMode bool      `json:"scaffolded"`   // Whether file was created in scaffold mode (won't overwrite)
		GeneratedAt  time.Time `json:"generated_at"` // When this file entry was created/updated
	}
)

// HashContent generates a SHA256 hash of the provided data.
// Used to detect if file contents have changed since generation.
func HashContent(data []byte) string {
	hash := sha256.Sum256(data)
	return hex.EncodeToString(hash[:])
}
