# Ref: https://github.com/apps/settings
repository:
  allow_merge_commit: false
  delete_branch_on_merge: true
  # TODO, make dynamic.
  topics:
    - golang
    - go-kit
    - dev-tool
  private: true
  has_wiki: false
  has_downloads: false
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      required_status_checks: null
      enforce_admins: true
      restrictions: null
