- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes

- name: Enable fail2ban service
  systemd:
    name: fail2ban
    enabled: yes
    state: started

- name: Deploy fail2ban configuration
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'

- name: Restart fail2ban to apply configuration
  systemd:
    name: fail2ban
    state: restarted
