package scaffold

import (
	"errors"
	"fmt"
	"io"
	"os"
	"testing"
	"text/template"

	"github.com/goccy/go-json"
	"github.com/goccy/go-yaml"
	"github.com/spf13/afero"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.uber.org/mock/gomock"

	"github.com/ainsleydev/webkit/internal/manifest"
	"github.com/ainsleydev/webkit/internal/mocks"
)

func setup(t *testing.T) *FileGenerator {
	t.Helper()

	fs := afero.NewMemMapFs()
	gen := New(fs, manifest.NewTracker())

	if !testing.Verbose() {
		gen.Printer.SetWriter(io.Discard)
	}

	return gen
}

func TestFileGenerator_Bytes(t *testing.T) {
	t.Run("MkdirAll Fails (read-only fs)", func(t *testing.T) {
		gen := setup(t)
		gen.fs = afero.NewReadOnlyFs(afero.NewMemMapFs())

		err := gen.Bytes("dir/file.txt", []byte("hello"))
		assert.Error(t, err, "Expected error writing to read-only FS")
	})

	t.Run("WriteFile fails (path is directory)", func(t *testing.T) {
		gen := setup(t)

		ctrl := gomock.NewController(t)
		mock := mocks.NewMockFS(ctrl)

		mock.EXPECT().MkdirAll(gomock.All(), os.ModePerm).Return(nil)
		mock.EXPECT().Stat(gomock.Any()).Return(nil, errors.New("error"))
		mock.EXPECT().OpenFile(gomock.Any(), gomock.Any(), gomock.Any()).Return(nil, errors.New("error"))

		gen.fs = mock

		err := gen.Bytes("dir/file.txt", []byte("hello"))
		assert.Error(t, err, "Expected error writing to path that is a directory")
	})

	t.Run("Updates Existing File", func(t *testing.T) {
		gen := setup(t)
		fs := afero.NewMemMapFs()
		gen.fs = fs

		path := "dir/file.txt"
		initialData := []byte("old content")
		newData := []byte("new content")

		// Pre-create the file so it exists.
		err := afero.WriteFile(fs, path, initialData, os.ModePerm)
		require.NoError(t, err)

		err = gen.Bytes(path, newData, WithoutNotice())
		assert.NoError(t, err)

		// Check the file content was updated.
		got, readErr := afero.ReadFile(fs, path)
		assert.NoError(t, readErr)
		assert.Equal(t, string(newData), string(got))

		// TODO: Check printer output
	})

	t.Run("Appends To Manifest", func(t *testing.T) {
		gen := setup(t)
		gen.fs = afero.NewMemMapFs()

		data := []byte("hello")
		err := gen.Bytes("dir/file.txt", data, WithTracking("source"))
		assert.NoError(t, err)
		assert.NotEmpty(t, gen.manifest)

		err = gen.manifest.Save(gen.fs)
		assert.NoError(t, err)

		mani, err := manifest.Load(gen.fs)
		assert.NoError(t, err)

		entry := mani.Files["dir/file.txt"]
		assert.Equal(t, "dir/file.txt", entry.Path)
		assert.Equal(t, "source", entry.Source)
		assert.False(t, entry.ScaffoldMode)
	})

	t.Run("Valid Write", func(t *testing.T) {
		gen := setup(t)
		gen.fs = afero.NewMemMapFs()

		data := []byte("hello")
		err := gen.Bytes("dir/file.txt", data, WithoutNotice())
		assert.NoError(t, err, "Expected successful write")

		got, readErr := afero.ReadFile(gen.fs, "dir/file.txt")
		assert.NoError(t, readErr)
		assert.Equal(t, data, got)
	})

	t.Run("Valid With Notice", func(t *testing.T) {
		gen := setup(t)
		gen.fs = afero.NewMemMapFs()

		data := []byte("MY_KEY=1234")
		err := gen.Bytes("dir/.env", data)
		assert.NoError(t, err, "Expected successful write")

		got, readErr := afero.ReadFile(gen.fs, "dir/.env")
		assert.NoError(t, readErr)

		want := `# Code generated by webkit; DO NOT EDIT.
MY_KEY=1234`
		assert.Equal(t, want, string(got))
	})
}

func TestFileGenerator_Template(t *testing.T) {
	path := "file.txt"
	gitIgnoreTpl := template.Must(template.New("gitignore").Parse(".DS_Store"))

	t.Run("Skips Scaffolding", func(t *testing.T) {
		gen := setup(t)

		err := afero.WriteFile(gen.fs, path, []byte("data"), os.ModePerm)
		require.NoError(t, err)

		err = gen.Template(path, gitIgnoreTpl, nil, WithScaffoldMode())
		assert.NoError(t, err, "Scaffold is skipped, file exists")
	})

	t.Run("Template Fails", func(t *testing.T) {
		gen := setup(t)
		tpl := template.Must(template.New("test").Parse("{{.NonExistentField.Method}}"))

		err := gen.Template(path, tpl, struct{}{})
		assert.Error(t, err, "Should return error when template execution fails")
		assert.ErrorContains(t, err, "executing template")
	})

	t.Run("Generates Successfully", func(t *testing.T) {
		gen := setup(t)
		err := gen.Template(".gitignore", gitIgnoreTpl, nil)
		assert.NoError(t, err)

		got, err := afero.ReadFile(gen.fs, ".gitignore")
		assert.NoError(t, err)

		want := "# Code generated by webkit; DO NOT EDIT.\n.DS_Store"
		assert.Equal(t, want, string(got))
	})
}

func TestFileGenerator_JSON(t *testing.T) {
	path := "file.json"
	jsonData := map[string]any{"project": "ainsley.dev"}
	jsonDataBytes, err := json.Marshal(jsonData)
	require.NoError(t, err)

	t.Run("Skips Scaffolding", func(t *testing.T) {
		gen := setup(t)

		err = afero.WriteFile(gen.fs, path, jsonDataBytes, os.ModePerm)
		require.NoError(t, err)

		err = gen.JSON(path, "", WithScaffoldMode())
		assert.NoError(t, err, "Scaffold is skipped, file exists")
	})

	t.Run("Encoder Failure", func(t *testing.T) {
		gen := setup(t)

		err = gen.JSON(path, make(chan int))
		assert.Error(t, err)
		assert.ErrorContains(t, err, "encoding file.json")
	})

	t.Run("Generates Successfully", func(t *testing.T) {
		gen := setup(t)

		err = gen.JSON(path, jsonData)
		assert.NoError(t, err)

		got, err := afero.ReadFile(gen.fs, path)
		assert.NoError(t, err)
		assert.JSONEq(t, string(jsonDataBytes), string(got))
	})
}

type badYAML struct{}

func (b badYAML) MarshalYAML() (interface{}, error) {
	return nil, fmt.Errorf("simulated failure")
}

func TestFileGenerator_YAML(t *testing.T) {
	path := "file.yaml"
	yamlData := map[string]any{"project": "ainsley.dev"}
	yamlDataBytes, err := yaml.Marshal(yamlData)
	require.NoError(t, err)

	t.Run("Skips Scaffolding", func(t *testing.T) {
		gen := setup(t)

		err = afero.WriteFile(gen.fs, path, yamlDataBytes, os.ModePerm)
		require.NoError(t, err)

		err = gen.YAML(path, "", WithScaffoldMode())
		assert.NoError(t, err, "Scaffold is skipped, file exists")
	})

	t.Run("Encoder Failure", func(t *testing.T) {
		gen := setup(t)

		err = gen.YAML("file.yaml", badYAML{})
		assert.Error(t, err)
		assert.ErrorContains(t, err, "encoding file.yaml")
	})

	t.Run("Generates Successfully", func(t *testing.T) {
		gen := setup(t)

		err = gen.YAML(path, yamlData)
		assert.NoError(t, err)

		got, pathErr := afero.ReadFile(gen.fs, path)
		assert.NoError(t, pathErr)

		want := "# Code generated by webkit; DO NOT EDIT.\nproject: ainsley.dev\n"
		assert.Equal(t, want, string(got))
	})
}

func TestFileGenerator_ShouldSkipScaffold_NotExists(t *testing.T) {
	gen := setup(t)

	path := "nonexistent.txt"
	got := gen.shouldSkipScaffold(path, ModeScaffold)
	assert.False(t, got)
}
