package scaffold

import (
	"fmt"
	"path/filepath"
)

// WebKitNotice is the notice outputted to all generated
// files within WebKit.
const WebKitNotice = "Code generated by webkit; DO NOT EDIT."

var commentMap = map[string]string{
	".go":           "//",
	".yaml":         "#",
	".yml":          "#",
	".env":          "#",
	".editorconfig": "#",
	".toml":         "#",
	".js":           "//",
	".html":         "<!-- %s -->",
	".md":           "<!-- %s -->",
	".json":         "",
}

// noticeForFile prepends a file-type-appropriate "do not edit"
// header to generated files dependent on the file type.
func noticeForFile(path string) string {
	ext := filepath.Ext(path)
	comment, exists := commentMap[ext]

	// If no mapping exists, use # as fallback
	if !exists {
		comment = "#"
	}

	// If comment is empty string (e.g., JSON), return empty notice
	if comment == "" {
		return ""
	}

	noticeText := WebKitNotice

	// handle HTML-style comments
	if comment == "<!-- %s -->" {
		return fmt.Sprintf(comment, noticeText) + "\n"
	}

	return fmt.Sprintf("%s %s\n", comment, noticeText)
}
