package scaffold

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestNoticeForFile(t *testing.T) {
	t.Parallel()

	tt := map[string]struct {
		input string
		want  string
	}{
		"Go File": {
			input: "main.go",
			want:  "// Code generated by webkit; DO NOT EDIT.\n",
		},
		"YAML File": {
			input: "config.yaml",
			want:  "# Code generated by webkit; DO NOT EDIT.\n",
		},
		"YML File": {
			input: "config.yml",
			want:  "# Code generated by webkit; DO NOT EDIT.\n",
		},
		"Editorconfig File": {
			input: ".editorconfig",
			want:  "# Code generated by webkit; DO NOT EDIT.\n",
		},
		"Toml File": {
			input: "settings.toml",
			want:  "# Code generated by webkit; DO NOT EDIT.\n",
		},
		"JS File": {
			input: "script.js",
			want:  "// Code generated by webkit; DO NOT EDIT.\n",
		},
		"HTML File": {
			input: "index.html",
			want:  "<!-- Code generated by webkit; DO NOT EDIT. -->\n",
		},
		"Markdown File": {
			input: "README.md",
			want:  "<!-- Code generated by webkit; DO NOT EDIT. -->\n",
		},
		"Unknown Extension File": {
			input: "file.unknown",
			want:  "# Code generated by webkit; DO NOT EDIT.\n",
		},
		"No Extension File": {
			input: "LICENSE",
			want:  "# Code generated by webkit; DO NOT EDIT.\n",
		},
		"Dockerignore File": {
			input: ".dockerignore",
			want:  "# Code generated by webkit; DO NOT EDIT.\n\n",
		},
	}

	for name, test := range tt {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			got := noticeForFile(test.input)
			assert.Equal(t, test.want, got)
		})
	}
}
