package scaffold

import (
	"fmt"
	"path/filepath"
)

// WebKitNotice is the notice outputted to all generated
// files within WebKit.
const WebKitNotice = "Code generated by webkit; DO NOT EDIT."

var commentMap = map[string]string{
	".go":           "//",
	".yaml":         "#",
	".yml":          "#",
	".env":          "#",
	".editorconfig": "#",
	".toml":         "#",
	".js":           "//",
	".html":         "<!-- %s -->",
	".md":           "<!-- %s -->",
}

// noticeForFile prepends a file-type-appropriate "do not edit"
// header to generated files dependent on the file type.
func noticeForFile(path string) string {
	ext := filepath.Ext(path)
	comment := commentMap[ext]
	if comment == "" {
		comment = "#" // fallback
	}

	noticeText := WebKitNotice

	// handle HTML-style comments
	if comment == "<!-- %s -->" {
		return fmt.Sprintf(comment, noticeText) + "\n"
	}

	notice := fmt.Sprintf("%s %s\n", comment, noticeText)

	// Add extra blank line for .dockerignore files
	if filepath.Base(path) == ".dockerignore" {
		notice += "\n"
	}

	return notice
}
