package scaffold

// Option is a function that configures write options
type Option func(*writeOptions)

// writeOptions holds configuration for write operations
type writeOptions struct {
	mode   WriteMode
	notice bool
}

// WithScaffoldMode sets the write mode for the operation
func WithScaffoldMode() Option {
	return func(opts *writeOptions) {
		opts.mode = ModeScaffold
	}
}

// WithNotice sets the generator to output the standard
// generated by WebKit notice.
func WithNotice(enabled bool) Option {
	return func(opts *writeOptions) {
		opts.notice = enabled
	}
}

// defaultOptions returns the default write options
func defaultOptions() *writeOptions {
	return &writeOptions{
		mode:   ModeGenerate,
		notice: false,
	}
}

// applyOptions applies the given options to writeOptions
func applyOptions(opts ...Option) *writeOptions {
	o := defaultOptions()
	for _, opt := range opts {
		opt(o)
	}
	return o
}
