package forms

// Country defines a key-value pair for a countr to be
// used in a select field.
type Country struct {
	Label string
	Value string
}

var countries = []Country{
	{Label: "Afghanistan", Value: "AF"},
	{Label: "Åland Islands", Value: "AX"},
	{Label: "Albania", Value: "AL"},
	{Label: "Algeria", Value: "DZ"},
	{Label: "American Samoa", Value: "AS"},
	{Label: "Andorra", Value: "AD"},
	{Label: "Angola", Value: "AO"},
	{Label: "Anguilla", Value: "AI"},
	{Label: "Antarctica", Value: "AQ"},
	{Label: "Antigua and Barbuda", Value: "AG"},
	{Label: "Argentina", Value: "AR"},
	{Label: "Armenia", Value: "AM"},
	{Label: "Aruba", Value: "AW"},
	{Label: "Australia", Value: "AU"},
	{Label: "Austria", Value: "AT"},
	{Label: "Azerbaijan", Value: "AZ"},
	{Label: "Bahamas", Value: "BS"},
	{Label: "Bahrain", Value: "BH"},
	{Label: "Bangladesh", Value: "BD"},
	{Label: "Barbados", Value: "BB"},
	{Label: "Belarus", Value: "BY"},
	{Label: "Belgium", Value: "BE"},
	{Label: "Belize", Value: "BZ"},
	{Label: "Benin", Value: "BJ"},
	{Label: "Bermuda", Value: "BM"},
	{Label: "Bhutan", Value: "BT"},
	{Label: "Bolivia", Value: "BO"},
	{Label: "Bosnia and Herzegovina", Value: "BA"},
	{Label: "Botswana", Value: "BW"},
	{Label: "Bouvet Island", Value: "BV"},
	{Label: "Brazil", Value: "BR"},
	{Label: "British Indian Ocean Territory", Value: "IO"},
	{Label: "Brunei Darussalam", Value: "BN"},
	{Label: "Bulgaria", Value: "BG"},
	{Label: "Burkina Faso", Value: "BF"},
	{Label: "Burundi", Value: "BI"},
	{Label: "Cambodia", Value: "KH"},
	{Label: "Cameroon", Value: "CM"},
	{Label: "Canada", Value: "CA"},
	{Label: "Cape Verde", Value: "CV"},
	{Label: "Cayman Islands", Value: "KY"},
	{Label: "Central African Republic", Value: "CF"},
	{Label: "Chad", Value: "TD"},
	{Label: "Chile", Value: "CL"},
	{Label: "China", Value: "CN"},
	{Label: "Christmas Island", Value: "CX"},
	{Label: "Cocos (Keeling) Islands", Value: "CC"},
	{Label: "Colombia", Value: "CO"},
	{Label: "Comoros", Value: "KM"},
	{Label: "Congo", Value: "CG"},
	{Label: "Congo, The Democratic Republic of the", Value: "CD"},
	{Label: "Cook Islands", Value: "CK"},
	{Label: "Costa Rica", Value: "CR"},
	{Label: "Cote D'Ivoire", Value: "CI"},
	{Label: "Croatia", Value: "HR"},
	{Label: "Cuba", Value: "CU"},
	{Label: "Cyprus", Value: "CY"},
	{Label: "Czech Republic", Value: "CZ"},
	{Label: "Denmark", Value: "DK"},
	{Label: "Djibouti", Value: "DJ"},
	{Label: "Dominica", Value: "DM"},
	{Label: "Dominican Republic", Value: "DO"},
	{Label: "Ecuador", Value: "EC"},
	{Label: "Egypt", Value: "EG"},
	{Label: "El Salvador", Value: "SV"},
	{Label: "Equatorial Guinea", Value: "GQ"},
	{Label: "Eritrea", Value: "ER"},
	{Label: "Estonia", Value: "EE"},
	{Label: "Ethiopia", Value: "ET"},
	{Label: "Falkland Islands (Malvinas)", Value: "FK"},
	{Label: "Faroe Islands", Value: "FO"},
	{Label: "Fiji", Value: "FJ"},
	{Label: "Finland", Value: "FI"},
	{Label: "France", Value: "FR"},
	{Label: "French Guiana", Value: "GF"},
	{Label: "French Polynesia", Value: "PF"},
	{Label: "French Southern Territories", Value: "TF"},
	{Label: "Gabon", Value: "GA"},
	{Label: "Gambia", Value: "GM"},
	{Label: "Georgia", Value: "GE"},
	{Label: "Germany", Value: "DE"},
	{Label: "Ghana", Value: "GH"},
	{Label: "Gibraltar", Value: "GI"},
	{Label: "Greece", Value: "GR"},
	{Label: "Greenland", Value: "GL"},
	{Label: "Grenada", Value: "GD"},
	{Label: "Guadeloupe", Value: "GP"},
	{Label: "Guam", Value: "GU"},
	{Label: "Guatemala", Value: "GT"},
	{Label: "Guernsey", Value: "GG"},
	{Label: "Guinea", Value: "GN"},
	{Label: "Guinea-Bissau", Value: "GW"},
	{Label: "Guyana", Value: "GY"},
	{Label: "Haiti", Value: "HT"},
	{Label: "Heard Island and Mcdonald Islands", Value: "HM"},
	{Label: "Holy See (Vatican City State)", Value: "VA"},
	{Label: "Honduras", Value: "HN"},
	{Label: "Hong Kong", Value: "HK"},
	{Label: "Hungary", Value: "HU"},
	{Label: "Iceland", Value: "IS"},
	{Label: "India", Value: "IN"},
	{Label: "Indonesia", Value: "ID"},
	{Label: "Iran, Islamic Republic Of", Value: "IR"},
	{Label: "Iraq", Value: "IQ"},
	{Label: "Ireland", Value: "IE"},
	{Label: "Isle of Man", Value: "IM"},
	{Label: "Israel", Value: "IL"},
	{Label: "Italy", Value: "IT"},
	{Label: "Jamaica", Value: "JM"},
	{Label: "Japan", Value: "JP"},
	{Label: "Jersey", Value: "JE"},
	{Label: "Jordan", Value: "JO"},
	{Label: "Kazakhstan", Value: "KZ"},
	{Label: "Kenya", Value: "KE"},
	{Label: "Kiribati", Value: "KI"},
	{Label: "Democratic People's Republic of Korea", Value: "KP"},
	{Label: "Korea, Republic of", Value: "KR"},
	{Label: "Kosovo", Value: "XK"},
	{Label: "Kuwait", Value: "KW"},
	{Label: "Kyrgyzstan", Value: "KG"},
	{Label: "Lao People's Democratic Republic", Value: "LA"},
	{Label: "Latvia", Value: "LV"},
	{Label: "Lebanon", Value: "LB"},
	{Label: "Lesotho", Value: "LS"},
	{Label: "Liberia", Value: "LR"},
	{Label: "Libyan Arab Jamahiriya", Value: "LY"},
	{Label: "Liechtenstein", Value: "LI"},
	{Label: "Lithuania", Value: "LT"},
	{Label: "Luxembourg", Value: "LU"},
	{Label: "Macao", Value: "MO"},
	{Label: "Macedonia, The Former Yugoslav Republic of", Value: "MK"},
	{Label: "Madagascar", Value: "MG"},
	{Label: "Malawi", Value: "MW"},
	{Label: "Malaysia", Value: "MY"},
	{Label: "Maldives", Value: "MV"},
	{Label: "Mali", Value: "ML"},
	{Label: "Malta", Value: "MT"},
	{Label: "Marshall Islands", Value: "MH"},
	{Label: "Martinique", Value: "MQ"},
	{Label: "Mauritania", Value: "MR"},
	{Label: "Mauritius", Value: "MU"},
	{Label: "Mayotte", Value: "YT"},
	{Label: "Mexico", Value: "MX"},
	{Label: "Micronesia, Federated States of", Value: "FM"},
	{Label: "Moldova, Republic of", Value: "MD"},
	{Label: "Monaco", Value: "MC"},
	{Label: "Mongolia", Value: "MN"},
	{Label: "Montenegro", Value: "ME"},
	{Label: "Montserrat", Value: "MS"},
	{Label: "Morocco", Value: "MA"},
	{Label: "Mozambique", Value: "MZ"},
	{Label: "Myanmar", Value: "MM"},
	{Label: "Namibia", Value: "NA"},
	{Label: "Nauru", Value: "NR"},
	{Label: "Nepal", Value: "NP"},
	{Label: "Netherlands", Value: "NL"},
	{Label: "Netherlands Antilles", Value: "AN"},
	{Label: "New Caledonia", Value: "NC"},
	{Label: "New Zealand", Value: "NZ"},
	{Label: "Nicaragua", Value: "NI"},
	{Label: "Niger", Value: "NE"},
	{Label: "Nigeria", Value: "NG"},
	{Label: "Niue", Value: "NU"},
	{Label: "Norfolk Island", Value: "NF"},
	{Label: "Northern Mariana Islands", Value: "MP"},
	{Label: "Norway", Value: "NO"},
	{Label: "Oman", Value: "OM"},
	{Label: "Pakistan", Value: "PK"},
	{Label: "Palau", Value: "PW"},
	{Label: "Palestinian Territory, Occupied", Value: "PS"},
	{Label: "Panama", Value: "PA"},
	{Label: "Papua New Guinea", Value: "PG"},
	{Label: "Paraguay", Value: "PY"},
	{Label: "Peru", Value: "PE"},
	{Label: "Philippines", Value: "PH"},
	{Label: "Pitcairn", Value: "PN"},
	{Label: "Poland", Value: "PL"},
	{Label: "Portugal", Value: "PT"},
	{Label: "Puerto Rico", Value: "PR"},
	{Label: "Qatar", Value: "QA"},
	{Label: "Reunion", Value: "RE"},
	{Label: "Romania", Value: "RO"},
	{Label: "Russian Federation", Value: "RU"},
	{Label: "Rwanda", Value: "RW"},
	{Label: "Saint Helena", Value: "SH"},
	{Label: "Saint Kitts and Nevis", Value: "KN"},
	{Label: "Saint Lucia", Value: "LC"},
	{Label: "Saint Pierre and Miquelon", Value: "PM"},
	{Label: "Saint Vincent and the Grenadines", Value: "VC"},
	{Label: "Samoa", Value: "WS"},
	{Label: "San Marino", Value: "SM"},
	{Label: "Sao Tome and Principe", Value: "ST"},
	{Label: "Saudi Arabia", Value: "SA"},
	{Label: "Senegal", Value: "SN"},
	{Label: "Serbia", Value: "RS"},
	{Label: "Seychelles", Value: "SC"},
	{Label: "Sierra Leone", Value: "SL"},
	{Label: "Singapore", Value: "SG"},
	{Label: "Slovakia", Value: "SK"},
	{Label: "Slovenia", Value: "SI"},
	{Label: "Solomon Islands", Value: "SB"},
	{Label: "Somalia", Value: "SO"},
	{Label: "South Africa", Value: "ZA"},
	{Label: "South Georgia and the South Sandwich Islands", Value: "GS"},
	{Label: "South Sudan", Value: "SS"},
	{Label: "Spain", Value: "ES"},
	{Label: "Sri Lanka", Value: "LK"},
	{Label: "Sudan", Value: "SD"},
	{Label: "Suriname", Value: "SR"},
	{Label: "Svalbard and Jan Mayen", Value: "SJ"},
	{Label: "Swaziland", Value: "SZ"},
	{Label: "Sweden", Value: "SE"},
	{Label: "Switzerland", Value: "CH"},
	{Label: "Syrian Arab Republic", Value: "SY"},
	{Label: "Taiwan, Province of China", Value: "TW"},
	{Label: "Tajikistan", Value: "TJ"},
	{Label: "Tanzania, United Republic of", Value: "TZ"},
	{Label: "Thailand", Value: "TH"},
	{Label: "Timor-Leste", Value: "TL"},
	{Label: "Togo", Value: "TG"},
	{Label: "Tokelau", Value: "TK"},
	{Label: "Tonga", Value: "TO"},
	{Label: "Trinidad and Tobago", Value: "TT"},
	{Label: "Tunisia", Value: "TN"},
	{Label: "Turkey", Value: "TR"},
	{Label: "Turkmenistan", Value: "TM"},
	{Label: "Turks and Caicos Islands", Value: "TC"},
	{Label: "Tuvalu", Value: "TV"},
	{Label: "Uganda", Value: "UG"},
	{Label: "Ukraine", Value: "UA"},
	{Label: "United Arab Emirates", Value: "AE"},
	{Label: "United Kingdom", Value: "GB"},
	{Label: "United States", Value: "US"},
	{Label: "United States Minor Outlying Islands", Value: "UM"},
	{Label: "Uruguay", Value: "UY"},
	{Label: "Uzbekistan", Value: "UZ"},
	{Label: "Vanuatu", Value: "VU"},
	{Label: "Venezuela", Value: "VE"},
	{Label: "Viet Nam", Value: "VN"},
	{Label: "Western Sahara", Value: "EH"},
	{Label: "Yemen", Value: "YE"},
	{Label: "Zambia", Value: "ZM"},
	{Label: "Zimbabwe", Value: "ZW"},
}
