// Package main provides the agents command for generating WebKit's root AGENTS.md file.
//
// This command is specifically for WebKit's own documentation (this repository), not for
// webkit-enabled repositories. It generates the root AGENTS.md file by combining:
//   - WebKit-specific content from docs/AGENTS.md (tool description, build commands, etc.)
//   - Code style guidelines from internal/gen/docs/CODE_STYLE.md (synced from ainsley.dev)
//
// # Usage
//
// Generate WebKit's AGENTS.md:
//
//	go run cmd/agents/main.go
//
// Or use the pnpm script:
//
//	pnpm agents:gen
//
// The generated file will be written to AGENTS.md at the repository root with a
// "Code generated by webkit; DO NOT EDIT" notice at the top.
package main
