// Package main provides the agents command for generating WebKit's root AGENTS.md file.
//
// This command is specifically for WebKit's own documentation (this repository), not for
// webkit-enabled repositories. It generates the root AGENTS.md file by combining:
//   - WebKit-specific content from docs/AGENTS.md (tool description, build commands, etc.)
//   - Code style guidelines from internal/gen/docs/CODE_STYLE.md (synced from ainsley.dev)
//
// # Why separate from the webkit CLI?
//
// The webkit CLI (internal/cmd/docs/agents.go) is designed to generate documentation for
// webkit-enabled repositories that use app.json manifests. Using the webkit CLI to generate
// WebKit's own documentation would create a circular dependency where WebKit would need to
// use itself to generate its own docs.
//
// This separation ensures:
//   - No circular dependencies
//   - Clear separation of concerns
//   - WebKit can generate its docs independently
//   - webkit-enabled repos use the webkit CLI for their docs
//
// # Usage
//
// Generate WebKit's AGENTS.md:
//
//	go run cmd/agents/main.go
//
// Or use the pnpm script:
//
//	pnpm agents:gen
//
// The generated file will be written to AGENTS.md at the repository root with a
// "Code generated by webkit; DO NOT EDIT" notice at the top.
package main
