package outputs

import (
	"encoding/json"

	"github.com/spf13/afero"
)

const (
	// FilePath is the path to the outputs file written by Terraform.
	FilePath = ".webkit/outputs.json"
)

type (
	// WebkitOutputs represents the structure of .webkit/outputs.json
	// generated by Terraform after infrastructure provisioning.
	WebkitOutputs struct {
		Monitoring MonitoringOutputs `json:"monitoring"`
		Slack      SlackOutputs      `json:"slack"`
	}
	// MonitoringOutputs contains Peekaping monitor data for status badges.
	// Note: Monitor maps use map[string]any for Go template compatibility
	// with sprig functions (keys, index).
	MonitoringOutputs struct {
		PeekapingEndpoint string         `json:"peekaping_endpoint"`
		StatusPageURL     string         `json:"status_page_url"`
		HTTPMonitors      map[string]any `json:"http_monitors"`
		DNSMonitors       map[string]any `json:"dns_monitors"`
		PushMonitors      map[string]any `json:"push_monitors"`
	}
	// SlackOutputs contains Slack channel information.
	SlackOutputs struct {
		ChannelName string `json:"channel_name"`
		ChannelID   string `json:"channel_id"`
	}
)

// Load attempts to load the .webkit/outputs.json file.
// Returns nil if the file doesn't exist or can't be parsed.
func Load(fs afero.Fs) *WebkitOutputs {
	data, err := afero.ReadFile(fs, FilePath)
	if err != nil {
		return nil
	}

	var outputs WebkitOutputs
	if err = json.Unmarshal(data, &outputs); err != nil {
		return nil
	}

	return &outputs
}
