package outputs

import (
	"encoding/json"

	"github.com/spf13/afero"
)

const (
	// FilePath is the path to the outputs file written by Terraform.
	FilePath = ".webkit/outputs.json"
)

type (
	// WebkitOutputs represents the structure of .webkit/outputs.json
	// generated by Terraform after infrastructure provisioning.
	WebkitOutputs struct {
		PeekapingEndpoint string       `json:"peekaping_endpoint"`
		Monitors          []Monitor    `json:"monitors"`
		Slack             SlackOutputs `json:"slack"`
	}
	// Monitor represents a single Peekaping monitor.
	Monitor struct {
		ID   string `json:"id"`
		Name string `json:"name"`
		Type string `json:"type"`
	}
	// SlackOutputs contains Slack channel information.
	SlackOutputs struct {
		ChannelName string `json:"channel_name"`
		ChannelID   string `json:"channel_id"`
	}
)

// Load attempts to load the .webkit/outputs.json file.
// Returns nil if the file doesn't exist or can't be parsed.
func Load(fs afero.Fs) *WebkitOutputs {
	data, err := afero.ReadFile(fs, FilePath)
	if err != nil {
		return nil
	}

	var outputs WebkitOutputs
	if err = json.Unmarshal(data, &outputs); err != nil {
		return nil
	}

	return &outputs
}
