package main

import (
	"flag"
	"fmt"
	"os"
	"time"

	"github.com/spf13/afero"

	"github.com/ainsleydev/webkit/internal/manifest"
	"github.com/ainsleydev/webkit/internal/printer"
	"github.com/ainsleydev/webkit/internal/scaffold"
)

func main() {
	var (
		versionFlag = flag.String("version", "", "Version string (e.g., v1.0.0)")
		commitFlag  = flag.String("commit", "", "Git commit hash")
		dateFlag    = flag.String("date", "", "Build date")
		builtByFlag = flag.String("builtby", "local", "Built by (e.g., goreleaser, local)")
	)

	flag.Parse()

	// Use defaults if not provided
	version := getOrDefault(*versionFlag, "v0.0.1-dev")
	commit := getOrDefault(*commitFlag, "none")
	date := getOrDefault(*dateFlag, time.Now().Format(time.RFC3339))
	builtBy := getOrDefault(*builtByFlag, "local")

	// Create filesystem and generator
	fs := afero.NewOsFs()
	console := printer.New(os.Stdout)
	tracker := manifest.NewTracker()
	gen := scaffold.New(fs, tracker, console)

	// Generate version file content
	content := fmt.Sprintf(`// Code generated by WebKit version generator. DO NOT EDIT.
package version

// generatedVersion contains the version information injected at build time.
const (
	generatedVersion = %q
	generatedCommit  = %q
	generatedDate    = %q
	generatedBuiltBy = %q
)
`, version, commit, date, builtBy)

	// Write the generated file
	if err := gen.Code("internal/version/version.gen.go", content); err != nil {
		console.Error(fmt.Sprintf("Failed to generate version file: %s", err))
		os.Exit(1)
	}

	console.Success(fmt.Sprintf("Generated version.gen.go with version: %s", version))
}

func getOrDefault(value, defaultValue string) string {
	if value == "" {
		return defaultValue
	}
	return value
}
