name: Dispatch Guidelines Update

on:
  repository_dispatch:
    types: [ guidelines-updated ]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-docs:
    name: Update documentation from guidelines
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup CI environment
        uses: ./.github/actions/setup
        with:
          integration: false

      - name: Install dependencies
        run: pnpm install

      - name: Generate guideline files
        run: go run cmd/docs/main.go

      - name: Generate AGENTS.md
        run: pnpm webkit agents generate

      - name: Check for changes
        id: changes
        run: |
          git diff --quiet AGENTS.md internal/gen/docs/ || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Create GitHub App token
        if: steps.changes.outputs.has_changes == 'true'
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: 2161597
          private-key: ${{ secrets.ORG_GITHUB_APP_PRIVATE_KEY }}

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: 'docs: Updating developer guidelines from ainsley.dev'
          title: 'docs: Updating developer guidelines'
          body: |
            ## Summary
            - Automated sync of developer guidelines from ainsley.dev
            - Generated guideline files updated in `internal/gen/docs/`
            - Root AGENTS.md regenerated from latest guidelines

            🤖 Generated with ainsley.dev bot
          branch: guidelines/update-${{ github.run_id }}
          base: main
          add-paths: |
            AGENTS.md
            internal/gen/docs/*.md
