name: Lint

on:
    workflow_dispatch:
    pull_request:
        branches: [ main ]

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: [ 1.22.4 ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: ${{ matrix.go-version }}

            -   name: Setup Biome
                uses: biomejs/setup-biome@v2
                with:
                    version: latest

            -   name: Install Dependencies
                run: go mod tidy

            -   name: Lint Go
                uses: golangci/golangci-lint-action@v6
                with:
                    version: latest
                    skip-cache: true
                    args: --verbose
                    working-directory: ./

            -   name: Biome
                run: biome ci .

            -   name: Diff
                run: git diff
