name: Publish

on:
  push:
    branches:
      - main

# Only allow one publish workflow to run at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup CI environment
        uses: ./.github/actions/setup

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Build application
        run: pnpm turbo run build

      - name: Create GitHub App token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: 2161597
          private-key: ${{ secrets.ORG_GITHUB_APP_PRIVATE_KEY }}

      - name: Create release PR or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          publish: pnpm changeset:publish
          commit: 'chore: Updating package versions'
          title: 'chore: Updating package versions'
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.ORG_NPM_TOKEN }}

      - name: Publish summary
        if: steps.changesets.outputs.published == 'true'
        run: |
          echo "## Published Packages" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The following packages were published:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.changesets.outputs.publishedPackages }}' | jq -r '.[] | "- **\(.name)** version \(.version)"' >> $GITHUB_STEP_SUMMARY
