name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup CI environment
        uses: ./.github/actions/setup

      - name: Test
        run: go test ./... -race -coverprofile=./coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          verbose: true

      - name: Diff
        run: git diff
